name:                AMASH-fetcher
version:             0.1.0.0
github:              "ob-fun-ws18/studienarbeit-amash"
license:             BSD3
author:              "Sven Schatter"
maintainer:          "sven.schatter@gmail.com"
copyright:           "2018 Sven Schatter"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ob-fun-ws18/studienarbeit-amash#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring
- http-conduit

library:
  source-dirs: src

executables:
  AMASH-fetcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AMASH-fetcher

tests:
  AMASH-fetcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AMASH-fetcher
    - hspec
    - QuickCheck

benchmarks:
  AMASH-fetcher-benchmark:
    main: Bench.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AMASH-fetcher
    - criterion
